-- SecurePaper: Supabase database schema
-- Recommended architecture:
-- Flask backend uses SUPABASE_SERVICE_ROLE_KEY kept only in .env.
-- Therefore database RLS can remain enabled and the backend can enforce
-- the application's custom Flask RBAC.

create table if not exists public.users (
    id bigint generated by default as identity primary key,
    username text unique not null,
    password_hash text not null,
    role text not null check (
        role in ('SETTER','MODERATOR','RELEASE_OFFICER','EXAM_CENTRE','ADMIN')
    ),
    examination_centre text,
    active boolean default true,
    created_at timestamptz default now()
);

create table if not exists public.question_papers (
    id bigint generated by default as identity primary key,
    original_name text not null,
    storage_path text not null,
    sha256 text not null,
    created_by bigint references public.users(id),
    scheduled_release timestamptz,
    examination_centre text,
    status text not null default 'PENDING' check (
        status in ('PENDING','APPROVED','REJECTED','RELEASED')
    ),
    approved_by bigint references public.users(id),
    approved_at timestamptz,
    rejection_reason text,
    released_at timestamptz,
    created_at timestamptz default now()
);

create table if not exists public.audit_logs (
    id bigint generated by default as identity primary key,
    username text,
    action text not null,
    paper_id bigint references public.question_papers(id),
    details text,
    ip_address text,
    created_at timestamptz default now()
);

-- Security baseline: RLS stays ON.
alter table public.users enable row level security;
alter table public.question_papers enable row level security;
alter table public.audit_logs enable row level security;

-- The Flask server uses the service-role key, so it bypasses RLS.
-- Do NOT put the service-role key in browser JavaScript or GitHub.
-- No public/anon policies are required for the backend.

-- Storage bucket:
-- Create a PRIVATE bucket named:
-- question-papers
--
-- Suggested bucket limits:
-- File size: 10 MB (or a value suitable for your project)
-- MIME type: application/octet-stream
-- Public bucket: OFF
--
-- The encrypted object is intentionally stored as application/octet-stream.


-- Existing databases created before the Exam Centre role was added:
-- run these ALTER statements once in Supabase SQL Editor.
alter table public.users drop constraint if exists users_role_check;
alter table public.users add constraint users_role_check
    check (role in ('SETTER','MODERATOR','RELEASE_OFFICER','EXAM_CENTRE','ADMIN'));

alter table public.users add column if not exists examination_centre text;
